---
title: Test Driven Development
desc: Diving deeper into Testing and Quality
hwref: week11
cat: testing
slides: true
---
:h2 Logistics

* Checkin Questions
* Look at :topic_link :poro_service_objects

:slide_title Term Projects Discussion

* Review of key dates: :section_link :intro :term_project

:slide_title Donald Knuth quote

* Interesting from an old archival [letter between Knuth and Emde Boas](https://staff.fnwi.uva.nl/p.vanemdeboas/knuthnote.pdf)
* Knuth very famous, Emde Boas, not so much.
* If you look at the attached paper you also see what I think is one of the very earliest uses of classes. It is on Figure 2: Page 1 of classroom note.

<a href="https://staff.fnwi.uva.nl/p.vanemdeboas/knuthnote.pdf"><img src="/content/topics/images/bewarebugs.jpg" class="img-thumbnail" style="height:300px;"/></a>

:slide_title Introduction to Testing
:topic_include :testing_intro

#### Some examples
* Let's take a look at: [Dumb Factorial Implementation](https://github.com/pitosalas/tdd_demo/blob/master/tdd_demo.rb)
* What other tests can we do to test this Factorial class?
* There are a huge variety of tools and techniques to avoid repetitious coding
* We will be using the built-in unit testing framework called "minitest"
* For this course focus ONLY on unit testing

#### Testing a full ruby class
* Let's take a look at <%= link_to_topic :money_class_test_example %> or [PlayingCard Class](https://github.com/pitosalas/tdd_demo/blob/master/playingcard.rb)
* Break into groups and come up with a list of tests that you would write

### Look at next class
* Look at homework <%= link_to_next_lecture %>
