---
title: CSS in the wild
desc: More in depth introduction to CSS and it's role in web based applications.
cat: rails
slides: true
---
:h2 Logistics

* Let's collect questions to ask a real-world software engineer working at a software company

:slide_bigtitle Mitchell Dodell - Brandeis Alum, now at Hubspot.

:topic_include :mitchell_dodell

:slide_bigtitle Continuing from last class

* :topic_link :erb
* :topic_link :json

:topic_include :css

:topic_include :bootstrap

:lecture_end