---
title: Testing 2
desc: We continue on TDD from the previous class
cat: testing
slides: true
---
:slide_bigtitle Going deeper on testing Continued

:topic_include :mocking

:slide_bigtitle Data and examples

* :topic_link :testing_data
* :topic_link :testing_in_rails
* :topic_link :hands_on_rails_test


:slide_title Testing a full ruby class

* Let's take a look at :topic_link :money_class_test_example or [PlayingCard Class](https://github.com/pitosalas/tdd_demo/blob/master/playingcard.rb)
* Break into groups and come up with a list of tests that you would write
* Look at :topic_link :poro_service_objects


:lecture_end`