---
title: Hands On with Testing
desc: We get more specific about different types of test
cat: testing
slides: true
---
:slide_bigtitle Why Testing?

:image :bewarebugs

* Interesting from an old archival [letter between Knuth and Emde Boas](https://staff.fnwi.uva.nl/p.vanemdeboas/knuthnote.pdf)
* Knuth very famous, Emde Boas, not so much.
* If you look at the attached paper you also see what I think is one of the very earliest uses of classes. It is on Figure 2: Page 1 of classroom note.

:slide_bigtitle Going deeper on testing Continued

:topic_include :testing_intro

:slide_bigtitle Going deeper

:topic_include :testing_pyramid

:topic_include :testing_reasons


:topic_include :mocking

:slide_bigtitle Data and examples

* :topic_link :testing_data
* :topic_link :testing_in_rails
* :topic_link :hands_on_rails_test


:slide_title Testing a full ruby class

* Let's take a look at :topic_link :money_class_test_example or [PlayingCard Class](https://github.com/pitosalas/tdd_demo/blob/master/playingcard.rb)
* Break into groups and come up with a list of tests that you would write
* Look at :topic_link :poro_service_objects


:lecture_end`