---
title: Programming Style
desc: Continue with programming style; also teams discuss products
cat: prod
slides: true
---
:h2 Logistics

:slide_bigtitle Programming Style

:topic_include :programming_style

:slide_title Looking at code

* Let's get permission from one of you to look at the code you submitted
* Be generous in your comments but also try to apply these or other principles

:lecture_end 